version: '3'
services:
  web:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .


    # Mapping of container port to host

    ports:
      - "8080:8080"

    environment:
      - "MYSQL_HOST_DOCKER=docker-mysql"

    # Link database container to app container
    # for reachability.
    links:
      - "docker-mysql:timeflip_guess"

  docker-mysql:

    # image to fetch from docker hub
    image: mysql
    command: --lower-case-table-names=1

    ports:
      - "3306:3306"

    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables.
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=spring"
      - "MYSQL_PASSWORD=uraniumjazz43"
      - "MYSQL_DATABASE=timeflip_guess"
